name: Run Weather Notebook

on:
  workflow_dispatch:    # Allows you to trigger the workflow manually
  schedule:
    # Run 3 times daily at 08:00, 16:00, and 22:00 UTC
    - cron: "0 8 * * *"
    - cron: "0 16 * * *"
    - cron: "0 22 * * *"

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib
          pip install jupyter nbconvert nbclient
      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute weatherData.ipynb --output executed_notebook.ipynb
      - name: Upload executed notebook as artifact
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_notebook.ipynb
