name: Run Weather Notebook

on:
  workflow_dispatch:    # Allows you to trigger the workflow manually
  schedule:
    # Run 3 times daily at 08:00, 16:00, and 22:00 UTC
    - cron: "0 8 * * *"
    - cron: "0 16 * * *"
    - cron: "0 22 * * *"

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib

      # Step 4: Execute the Jupyter notebook
      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace weatherData.ipynb

      # Step 5: Commit and push the executed notebook
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add weatherData.ipynb
          git commit -m "Update notebook with latest data [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
